src/objects/Custom_Data_Sync_Batch_Execution__c.object
<CustomObject>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Batch Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Results Generated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Data Sync Batch Execution</label>
    <nameField>
        <displayFormat>CDSBE-{0000000000}</displayFormat>
        <label>Custom Data Sync Batch Execution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Data Sync Batch Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Custom_Data_Sync_Field_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Preference_Scope__c</fullName>
        <defaultValue>&quot;User&quot;</defaultValue>
        <label>Preference Scope</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Batch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Custom_Data_Sync_Field_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Data Sync Field Preference</label>
    <nameField>
        <label>Field Api Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Data Sync Field Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomDataSyncBatchTest.cls
/*
 * created by : angel robles
 * created date : 1/25/2021
 */ 

@istest
public class CustomDataSyncBatchTest {
    
    @testsetup
    static void setup(){
        
        List<Custom_Data_Sync_Field_Preference__c> configFields = new List<Custom_Data_Sync_Field_Preference__c>{
          new Custom_Data_Sync_Field_Preference__c(Name = 'FirstName',User__c=UserInfo.getUserId(), preference_scope__c = 'User'),
          new Custom_Data_Sync_Field_Preference__c(Name = 'Email',User__c=UserInfo.getUserId(), preference_scope__c = 'User')  

        };
        insert configFields;
        
        insert new Contact(FirstName = 'angel', LastName='robles', email='angelmercedes@hotmail.com');
    }
    
    @istest
    public static void executeRecordsTest(){
        CustomDataSyncHelperTest.GenerateMockConfig();
        
        CustomDataSyncBatch b= new CustomDataSyncBatch(100, 'records',null, null);
        test.starttest();
        database.executeBatch(b, 1);
        test.stoptest();
        
        Custom_Data_Sync_Batch_Execution__c batchExecution = [select state__c from Custom_Data_Sync_Batch_Execution__c limit 1];
        
        system.assert(batchExecution.state__c== 'Complete');
    }
    
    @istest
    public static void executeProcessTest(){
        CustomDataSyncHelperTest.GenerateMockConfig();
        
         Custom_Data_Sync_Batch_Execution__c  executionRecord = new Custom_Data_Sync_Batch_Execution__c (start_time__c=datetime.now(), state__c='Created' );
        insert executionRecord;
        
        
        CustomDataSyncBatch b= new CustomDataSyncBatch(100, 'process',new list<object>{'superfakeid'}, executionRecord.id);
        test.starttest();
        database.executeBatch(b, 1);
        test.stoptest();
        
        Custom_Data_Sync_Batch_Execution__c batchExecution = [select state__c from Custom_Data_Sync_Batch_Execution__c  where id =:executionRecord.id];
        
        system.assert(batchExecution.state__c== 'Complete');
    }
    
    @istest
    public static void executeRecordsInProgressTest(){
        CustomDataSyncHelperTest.GenerateMockConfig();
        CustomDataSyncHelperTest.returnInProgressStatus = true;
         Custom_Data_Sync_Batch_Execution__c  executionRecord = new Custom_Data_Sync_Batch_Execution__c (start_time__c=datetime.now(), state__c='In Progress' );
        insert executionRecord;
        
        
        CustomDataSyncBatch b= new CustomDataSyncBatch(100, 'records',new list<object>{'superfakeid'}, executionRecord.id);
        test.starttest();
        database.executeBatch(b, 1);
        test.stoptest();
        
        Custom_Data_Sync_Batch_Execution__c batchExecution = [select state__c from Custom_Data_Sync_Batch_Execution__c  where id =:executionRecord.id];
        
        system.assert(batchExecution.state__c == 'In Progress');
    }
    
    @istest
    public static void executeProcessInProgressTest(){
        CustomDataSyncHelperTest.GenerateMockConfig();
        CustomDataSyncHelperTest.returnInProgressStatus = true;
         Custom_Data_Sync_Batch_Execution__c  executionRecord = new Custom_Data_Sync_Batch_Execution__c (start_time__c=datetime.now(), state__c='In Progress' );
        insert executionRecord;
        
        
        CustomDataSyncBatch b= new CustomDataSyncBatch(100, 'process',new list<object>{'superfakeid'}, executionRecord.id);
        test.starttest();
        database.executeBatch(b, 1);
        test.stoptest();
        
        Custom_Data_Sync_Batch_Execution__c batchExecution = [select state__c from Custom_Data_Sync_Batch_Execution__c  where id =:executionRecord.id];
        
        system.assert(batchExecution.state__c == 'In Progress');
    }
    
     @istest
    public static void CustomDataSyncBatchSchedulerTest(){
        CustomDataSyncHelperTest.GenerateMockConfig();
        boolean result = false;
        test.starttest();
        system.schedule('test schedule for me', '0 0 22 * * ? *', new CustomDataSyncBatchScheduler(10000));
        result = true;
        test.stoptest();
        
        
        system.assert(result);
    }
    
    
    

}